version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=sa-east-1
    volumes:
      - ./create_table.sh:/docker-entrypoint-initaws.d/create_table.sh