spring.application.name=mf-semi-joias
aws.endpoint=http://localhost:4566

logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.com.api.mfsemijoias_cadastracliente=DEBUG

spring.profiles.active=local

aws.dynamodb.profile=localstack
aws.dynamodb.region=sa-east-1
aws.dynamodb.endpoint=http://localhost:4566

spring.security.enabled=false
