name: CI/CD Pipeline

on:
  push: # Será acionado em qualquer push
  pull_request:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ github.ref_name }} # Identifica automaticamente a branch atual
          title: "Automated Pull Request"
          body: |
            Este PR foi criado automaticamente pelo workflow.
          commit-message: "feat: alterações automatizadas"
          base: develop
          always-create: true