jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy application
      run: |
        echo "Deploying application..."

    - name: Validate Token Permissions
      id: validate_token
      run: |
        echo "Validating token permissions..."
        response=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission)
        echo "Response: $response"
        permission=$(echo $response | jq -r '.permission')
        echo "permission=$permission" >> $GITHUB_ENV

    - name: Fetch all branches
      run: git fetch --all

    - name: Check for New Commits
      id: check_commits
      run: |
        echo "Checking for new commits..."
        new_commits=$(git rev-list --right-only --count origin/develop...origin/feature/flavio)
        echo "new_commits=$new_commits" >> $GITHUB_ENV

    - name: Debugging Information
      run: |
        echo "Debugging Information"
        git status
        git log -1
        ls -la
        cat .git/config