name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - develop
      - release/homolog
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

  deploy-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Deploy to develop server
        run: |
          echo "Deploying to develop server..."
          # Adicione aqui os comandos para fazer o deploy no servidor de desenvolvimento

  deploy-release-homolog:
    if: github.ref == 'refs/heads/release/homolog'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Deploy to homolog server
        run: |
          echo "Deploying to homolog server..."
          # Adicione aqui os comandos para fazer o deploy no servidor de homologação

  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Deploy to production server
        run: |
          echo "Deploying to production server..."
          # Adicione aqui os comandos para fazer o deploy no servidor de produção