name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy application
      run: |
        echo "Deploying application..."

    - name: Validate Token Permissions
      id: validate_token
      run: |
        echo "Validating token permissions..."
        response=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/collaborators/${{ github.actor }}/permission)
        echo "Response: $response"
        permission=$(echo $response | jq -r '.permission')
        echo "permission=$permission" >> $GITHUB_ENV

    - name: Fetch develop branch
      run: git fetch origin develop:develop

    - name: Check for New Commits
      id: check_commits
      run: |
        echo "Checking for new commits..."
        new_commits=$(git rev-list --right-only --count develop...${{ github.ref }})
        echo "new_commits=$new_commits" >> $GITHUB_ENV

    - name: Create Pull Request
      id: create_pr
      if: ${{ env.permission == 'write' || env.permission == 'admin' && env.new_commits != '0' }}
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Atualização automática
        branch: auto-pr-branch
        title: 'Pull request automático'
        body: 'Este pull request foi criado automaticamente pelo GitHub Actions.'
        base: develop
        branch-suffix: timestamp
        debug: true

    - name: Validate Pull Request Creation
      if: ${{ steps.create_pr.outputs.pull-request-url == '' }}
      run: |
        echo "Falha ao criar o Pull Request"
        exit 1

    - name: Pull Request Created Successfully
      if: ${{ steps.create_pr.outputs.pull-request-url != '' }}
      run: |
        echo "Pull Request criado com sucesso: ${{ steps.create_pr.outputs.pull-request-url }}"

    - name: Debugging Information
      run: |
        echo "Debugging Information"
        git status
        git log -1
        ls -la
        cat .git/config