name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*
      - develop
      - release/homolog
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Deploy to server
      run: |
        echo "Deploying to server..."
        # Adicione aqui os comandos para deploy, por exemplo, usando SCP, SSH, etc.
        # scp target/your-app.jar user@server:/path/to/deploy/
        # ssh user@server 'bash /path/to/deploy/deploy-script.sh'