name: ci-cd
        on:
          push:
            branches:
              - develop
          pull_request:
            branches:
              - develop
              - homolog

        jobs:
          build:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v2
              - name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                  java-version: '17'
                  distribution: 'adopt'
              - name: Build with maven
                run: mvn package
              - name: Run tests
                run: mvn test
              - name: Deploy
                run: mvn spring-boot:run