name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/*
      - bugfix/*
      - hotfix/*image: maven:3.6.0-jdk-17

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar

deploy:
  stage: deploy
  script:
    - echo "Deploying to produção..."
    - # Aqui você pode adicionar os comandos para deploy
  only:
    - main
      - develop
      - release/homolog
      - main

